### ISSUE TITLE
doens't parse date objects

### ISSUE THREAD

**Issue by mderazon** [sehrope/node-simple-encryptor#2]
Problem is that JSON.parse doesn't treat a date object that has been stringified any differently.

As a result, `object != decrypt(encrypt(object))` if object contains any date fields.

The solution is to use a date reviver while parsing.

Something like 
``` js
function dateReviver(key, value) {
    var a;
    if (typeof value === 'string') {
        a = /^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2}):(\d{2}(?:\.\d*)?)Z$/.exec(value);
        if (a) {
            return new Date(Date.UTC(+a[1], +a[2] - 1, +a[3], +a[4],
                            +a[5], +a[6]));
        }
    }
    return value;
};

JSON.parse(json, dateReviver)
```
 (source: https://msdn.microsoft.com/library/cc836466%28v=vs.94%29.aspx?f=255&MSPPError=-2147217396)

This handles dates in nested fields as well. It only parses fields as dates if they are in the same format produced by `Date.toISOString()` (which `JSON.stringify()` uses behind the scenes)

Let me know if you want me to send a patch

**Comment by sehrope** [comment]
Sure that sounds useful and PRs welcome!

Instead of special handling for Date types, how about adding an optional `reviver` property to `opts`? If set, then the `JSON.parse(...)` call would use it. It could be used to instantiate user-specified custom classes and the new property would be backwards compatible.

Ex:

    function myReviver(key, value) {
      // ... stuff to handle Date or other custom types here
    }

    var encryptor = require('simple-encryptor')({key: 't0ps3cret', reviver: myReviver});

**Comment by sehrope** [comment]
Closing out as this is covered by #3
