### ISSUE TITLE
node v6.9.4

### ISSUE THREAD

**Issue by retani** [sehrope/node-simple-encryptor#5]
I am getting `Error: secure random number generation not supported by this browser
use chrome, FireFox or Internet Explorer 11` using node v6.9.4 when initializing. However, I am not sure where this warning is issued

**Comment by sehrope** [comment]
You're trying to use this module client side, I'm guessing via browserify, in an older browser that doesn't support generation of secure random numbers.

Here's the source of the message: https://github.com/crypto-browserify/randombytes/blob/9b470ac1419e5545a5265238ccc5db8a7f1f8644/browser.js#L4

I don't think there's much of a work around here as in those older browsers there is no secure way to generate random numbers. As such there's no correct way to implement that function. You may be able to kludge a polyfill with `Math.random()` but it'd be horrendously insecure. Better off only supporting modern browsers that support those newer Crypto APIs.
